apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.auth.rootUsername | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.auth.rootPassword | quote }}