apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: logging

data:
  filebeat.yml: |
    filebeat.inputs:
    - type: container
      paths:
        - /var/log/containers/*.log

    output.elasticsearch:
      hosts: ["https://elasticsearch-es-http.logging.svc:9200"]

      username: elastic
      password: CHANGE_ME